### ISSUE TITLE
No '-main' function in dev_server

### ISSUE THREAD

**Issue by dfornika** [madvas/cljs-react-material-ui-example#1]
I get the following error & stacktrace (I've truncated it for brevity) when I do `lein run` on the 

```
Exception in thread "main" java.lang.Exception: Cannot find anything to run for: cljs-react-material-ui-example.dev-server, compiling:(/tmp/form-init7440310424212315599.clj:1:73)
    at clojure.lang.Compiler.load(Compiler.java:7391)
    at clojure.lang.Compiler.loadFile(Compiler.java:7317)
    at clojure.main$load_script.invokeStatic(main.clj:275)
```

I've found that I can fix it by wrapping the contents of `env/dev/clj/cljs_react_material_ui_example/dev_server.clj` (aside from the `ns` declaration) in a `-main` function declaration.

**Comment by arrterian** [comment]
@dfornika fixed in this PR https://github.com/madvas/cljs-react-material-ui-example/pull/3
